// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed logo.png
var resourceLogoPngData []byte
var resourceLogoPng = &fyne.StaticResource{
	StaticName:    "logo.png",
	StaticContent: resourceLogoPngData,
}
